language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: P5Fo5vq94651XRiEmM5t+vEYubTLe1oR+KmHLYR6nt0qrV5ULMkygND9VCxPFGgNAf4RrFrIPXaJCFmLq0Ou6ASpSaBQfgjlJKROkkIZ1DL0W668MAiCVnA6uL6alwxMIhC1stUZ5QM30ivQqqSRkv09KZOKY/mO4L2cSzcyC14gcfNCyJWfgFwemzk0+084xLqnbqTR6rFUxKFlB+N4Ti7tvVBFvqC2w+8ykW5bG7MtywbtCl0sWibRgWv4xOmUfwXDs514/yb7IH2GSm7lhjtof9n9InkD4Z7oP5w0plsQT+bVmDvJa6dbdTHz1seQH66CTSJ88q666uphftQKH98MYm6bCwOqozAW5PSUwQwbSvflBf+iWTv02sDYjfKUMWwwRk1a7ddfsCaH4A5MTOJ+xsnd7dbygx1Q8TuvibxHKcySvTJNJXyhuA3xi8T0fnNf41xmOK5VkYSUM+prfeR01tBqRsz9PoAN6WHGUE0n8s+mBVklAGzwR2OPk5p7I10UlfA89htdj1npCw1jpqysK3xCaHgXGTfY6oSyK3B+ttATAz/yBgDz372c1GSFXfGW474NFAv7YYY8BidAmYgoE98mJOYwtnaso+Dg5qfKDiWd8w2hxtFmWCGIKs4lwPkApeMC8FvO+4AnRy5Ig9AzAwK7LkH7oSQL44bDPwE=
  app: frozen-atoll-41769
  on:
    repo: willnix86/ppl
